// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * "42" → 42, "  3.5 " → 3.5, "" → "", "Q1" → "Q1".
 * @param {unknown} text
 * @returns {string | number}
 */
export declare function coerce(text: unknown): string | number;
/**
 * A cell's value: its `data-value`, else a `<data value>` or
 * `<time datetime>` that is its only content, else its text. So a cell can
 * show "$1.2M" or "Oct 4" and carry 1200000 or 2026-10-04.
 * @param {HTMLTableCellElement} cell
 * @returns {string | number}
 */
export declare function cellValue(cell: HTMLTableCellElement): string | number;
/**
 * A table's rows as objects. Column names are the header cells (`<thead>`'s
 * last row, else the first row's `<th>`s), or a header's `data-field`.
 *
 * A grid table (one row per item, one column per category, a value in each
 * cell, like a heatmap written out) is read with `columnField` and
 * `valueField`: each cell becomes its own row, `{ [corner]: row header,
 * [columnField]: column header, [valueField]: cell }`, where `corner` is the
 * top-left header's text (or "row"). Empty cells are skipped.
 * @param {HTMLTableElement} table
 * @param {{ columnField?: string | null, valueField?: string | null }} [shape]
 * @returns {Record<string, string | number>[]}
 */
export declare function readTable(table: HTMLTableElement, { columnField, valueField }?: {
    columnField?: string | null;
    valueField?: string | null;
}): Record<string, string | number>[];
/**
 * Rows from anything: an array or iterable of objects, or of arrays (keyed "0", "1", …).
 * @param {unknown} rows
 * @returns {Record<string, unknown>[]}
 */
export declare function normalize(rows: unknown): Record<string, unknown>[];
/**
 * A datalist's rows: one per `<option>`, with `value` (its `value`, else
 * its text), `label` (its `label`, else its text), and a field for each
 * `data-*` attribute, named as `dataset` names it (`data-start-week` is
 * `startWeek`). Text is read like a table cell's: "42" is 42.
 * @param {HTMLDataListElement} list
 * @returns {Record<string, string | number>[]}
 */
export declare function readDatalist(list: HTMLDataListElement): Record<string, string | number>[];
/**
 * The rows in a source element: a `<table>` (`shape` reads a grid table;
 * see readTable), a `<datalist>`, or a `<script type="application/json">`.
 * Text sources turn numeric text into numbers; JSON is used as written.
 * Throws on bad JSON.
 * @param {Element} element
 * @param {{ columnField?: string | null, valueField?: string | null }} [shape]
 * @returns {Record<string, unknown>[]}
 */
export declare function readSource(element: Element, shape?: {
    columnField?: string | null;
    valueField?: string | null;
}): Record<string, unknown>[];
