// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export { default as DataPlot } from "./data-plot/index.mjs";
export { default as PlotMarks } from "./plot-marks/index.mjs";
export { default as PlotLine } from "./plot-line/index.mjs";
export { default as PlotAxis } from "./plot-axis/index.mjs";
export { default as PlotLegend } from "./plot-legend/index.mjs";
export { default as ChernoffFace } from "./chernoff-face/index.mjs";
export { PlotLayer, DataLayer } from "./layer.mjs";
export { linear, band, position, color, nice, ticks, extent } from "./scale.mjs";
export { readTable, readDatalist, readSource } from "./data.mjs";
