// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** Marks the frame element (<data-plot>, under whatever tag name). */
export declare const FRAME: unique symbol;
/**
 * Makes a drawing accessible, following its data. A readable table already
 * says what the drawing shows, so the drawing is hidden from assistive
 * technology. Otherwise the drawing must say it: given an `aria-label` (or
 * `aria-labelledby`) it becomes `role="img"`; without one, a console warning.
 */
export declare function describe(host: any, readable: any, { hide, hasRows }?: {
    hasRows?: boolean | undefined;
    hide?: boolean | undefined;
}): void;
export declare class PlotLayer extends HTMLElement {
    #private;
    /**
     * The channels this layer reads (`x`, `x2`, `y`, `y2`, `color`, `size`), so the plot builds scales for them.
     * @protected
     */
    protected channels(): never[];
    /** The `<data-plot>` this layer is directly inside, or null. @type {HTMLElement | null} */
    get plot(): HTMLElement | null;
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(name: any, previous: any, value: any): void;
    /** Redraws soon: through its plot, or by itself when it can draw alone. Several requests in one task draw once. */
    requestRender(): any;
    /**
     * Draws outside a plot. Layers that can't (axes, legends) draw nothing.
     * @protected
     */
    protected renderAlone(): void;
    /**
     * Draws from the plot's `{ rows, scales, unit, describedByTable }`.
     * @protected
     */
    protected draw({ describedByTable }: {
        describedByTable: any;
    }): void;
}
export declare class DataLayer extends PlotLayer {
    #private;
    /** The rows drawn: its own (from `src`, a source inside it, or set here), else its plot's. Setting it replots, until `src` changes or it's set to null. Changing the array in place needs `requestRender()`. @type {object[]} */
    get data(): object[];
    set data(rows: object[]);
    /** Its own rows, or null when it uses its plot's. @type {object[] | null} */
    get ownRows(): object[] | null;
    /** True when its own data is a table assistive technology can read. @type {boolean} */
    get readable(): boolean;
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(name: any, previous: any, value: any): void;
    /**
     * Alone, there are no positions, but color and `:attr` scaling still apply; then it describes itself and fires `render`.
     * @protected
     */
    protected renderAlone(): void;
}
