// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Defines a property for each attribute on `Class.prototype`.
 * `spec` maps attribute names to "string", "boolean", or a number's default
 * (`{ ticks: 0 }` reads an absent or non-numeric attribute as 0).
 */
export declare function reflect(Class: any, spec: any): string[];
