// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export type Scale<T = number> = ((value: unknown) => T) & {
    type: string;
    domain: unknown[];
    bandwidth?: number;
    ticks: (count?: number) => unknown[];
};
/**
 * A scale: a function from a data value to a position from 0 to 1 (or, for
 * color, to a CSS color), with what it was built from.
 * @template [T=number]
 * @typedef {((value: unknown) => T) & { type: string, domain: unknown[], bandwidth?: number, ticks: (count?: number) => unknown[] }} Scale
 */
/** @param {unknown} value @returns {value is number} */
declare const isNumber: (value: unknown) => value is number;
/**
 * A "nice" tick step for a span divided into about `count` parts: 1, 2, or 5 × 10ⁿ.
 * @param {number} span
 * @param {number} count
 * @returns {number}
 */
export declare function tickStep(span: number, count: number): number;
/**
 * Widens [min, max] outward to whole tick steps.
 * @param {[number, number]} domain
 * @param {number} [count]
 * @returns {[number, number]}
 */
export declare function nice([min, max]: [number, number], count?: number): [number, number];
/**
 * Evenly stepped values from min to max, at a nice step.
 * @param {[number, number]} domain
 * @param {number} [count]
 * @returns {number[]}
 */
export declare function ticks([min, max]: [number, number], count?: number): number[];
/**
 * Continuous numbers: domain [min, max] → 0…1. Non-numbers map to NaN.
 * @param {[number, number]} domain
 * @returns {Scale}
 */
export declare function linear(domain: [number, number]): Scale;
/**
 * Distinct values, each given an equal band; a value maps to its band's center.
 * @param {Iterable<unknown>} values
 * @param {number} [padding] The share of each band left empty, 0–1. Default 0.2.
 * @returns {Scale}
 */
export declare function band(values: Iterable<unknown>, padding?: number): Scale;
export declare const PALETTE: string[];
/**
 * Categories → palette colors (in order of appearance), or numbers → a ramp between two colors.
 * @param {unknown[]} values
 * @param {{ palette?: string[], low?: string, high?: string }} [options]
 * @returns {Scale<string>}
 */
export declare function color(values: unknown[], { palette, low, high }?: {
    palette?: string[];
    low?: string;
    high?: string;
}): Scale<string>;
/**
 * [smallest, largest] of the finite numbers in `values`, or [0, 1] if there are none.
 * @param {Iterable<unknown>} values
 * @returns {[number, number]}
 */
export declare function extent(values: Iterable<unknown>): [number, number];
/**
 * A position scale for `values`: linear when they're all numbers, banded
 * otherwise. `spec` is the `x-domain`/`y-domain` attribute: "0 100", or
 * "0 auto" to pin one end, applied before rounding to nice ticks. `padding`
 * is a banded scale's empty share of each band.
 * @param {unknown[]} values
 * @param {string | null} [spec]
 * @param {number} [padding]
 * @returns {Scale}
 */
export declare function position(values: unknown[], spec?: string | null, padding?: number): Scale;
/**
 * Scales any numeric field to 0–1, for `:attr` bindings. A field a channel
 * already scales (in `fixed`, field → scale) uses that scale, so `:size`
 * and `size` agree; any other field spans its values across `rowSets`.
 * Results are clamped to 0–1.
 * @param {Record<string, unknown>[][]} rowSets
 * @param {Map<string, Scale>} [fixed]
 * @returns {(field: string, value: unknown) => number}
 */
export declare function unitScale(rowSets: Record<string, unknown>[][], fixed?: Map<string, Scale>): (field: string, value: unknown) => number;
export declare const isNumeric: typeof isNumber;
export {};
