// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** The rows of `element`, kept current: `listener(rows, error)` runs after each change. Throws if it can't be read now. */
export declare function subscribe(element: any, shape: any, listener: any): {
    readonly rows: any;
    unsubscribe(): void;
};
/**
 * An element's own data, by one rule everywhere:
 *
 * 1. `.data` (set from script) wins, until `src` changes or `.data` is set to null.
 * 2. Else `src="#id"`: a table, datalist, or JSON script in the page.
 * 3. Else a table, datalist, or JSON script inside the element.
 * 4. Else none (`rows` is null), and a layer uses its plot's rows.
 *
 * `onChange` runs when the rows change; errors fire `error` on the host.
 */
export declare class DataBinding {
    #private;
    constructor(host: any, onChange: any);
    /** The rows, or null when the element has no data of its own. */
    get rows(): null;
    /** The source element being read, if any. */
    get source(): null;
    /** True when the source is a table assistive technology can read: inside the host, or visible elsewhere. */
    get readable(): boolean;
    set property(rows: any);
    /** (Re)reads from the current source. Call when `src`, the shape attributes, or the host's children change. */
    connect(): void;
    disconnect(): void;
}
/** True if any of these mutation records added or removed a source element. */
export declare function sourceChildrenChanged(records: any): any;
