// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** Copies the template's content and records its bindings. Returns the copy's elements. */
export declare function stamp(template: any): any[];
/** Writes one row into a stamped copy. `unit(field, value)` scales a field's value to 0–1. */
export declare function bind(element: any, row: any, unit: any): void;
