// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Moves own properties that shadow the element's accessors back through
 * them: each is read, deleted, and assigned again. Covers every accessor with
 * a setter on the class's prototype chain (below `HTMLElement`), so a new
 * property needs no registration.
 * @param {HTMLElement} element
 */
export declare function upgradeProperties(element: HTMLElement): void;
